## Your key goes here
$OPENAI_API_ORG = 
$OPENAI_API_KEY = 

## OpenAI Example A
$headers = @{
  'Content-Type' = 'application/json'
  'Authorization' = "Bearer $OPENAI_API_KEY" 
  'OpenAI-Organization' =  $OPENAI_API_ORG
} 
$request = Invoke-RestMethod -Headers $headers -Uri  'https://api.openai.com/v1/models' 
$request.data.id 

## OpenAI Example B (generated by ChatGPT)
# Define the body
$body = @{
    "model" = "text-davinci-003"
    "prompt" = "I am a highly intelligent question answering bot. If you ask me a question that is rooted in truth, I will give you the answer. If you ask me a question that is nonsense, trickery, or has no clear answer, I will respond with `Unknown`.\n\nQ: What is human life expectancy in the United States?\nA: Human life expectancy in the United States is 78 years.\n\nQ: Who was president of the United States in 1955?\nA: Dwight D. Eisenhower was president of the United States in 1955.\n\nQ: Which party did he belong to?\nA: He belonged to the Republican Party.\n\nQ: What is the square root of banana?\nA: Unknown\n\nQ: How does a telescope work?\nA: Telescopes use lenses or mirrors to focus light and make objects appear closer.\n\nQ: Where were the 1992 Olympics held?\nA: The 1992 Olympics were held in Barcelona, Spain.\n\nQ: How many squigs are in a bonk?\nA: Unknown\n\nQ: Where is the Valley of Kings?\nA:"
    "temperature" = 0
    "max_tokens" = 100
    "top_p" = 1
    "frequency_penalty" = 0.0
    "presence_penalty" = 0.0
    "stop" = "\n"
}

# Convert the body to JSON
$bodyJson = $body | ConvertTo-Json

# Make the request
$response = Invoke-RestMethod -Uri "https://api.openai.com/v1/completions" -Method Post -Headers $headers -Body $bodyJson

# Display the response
$response
