query {
    myalias: __schema {
        types {
            name
            fields {
                name
                type {
                    ofType {
                        name
                    }
                }
            }
        }
    }
}