query {
    myalias: __schema {
        queryType {
            fields {
                name
                type {
                    name
                    ofType {
                        name
                    }
                }
                args {
                    name
                    type {
                        ofType {
                            name
                        }
                    }
                }
            }

        }
    }
}